### ISSUE TITLE
[SMF2.0]CAS update failed on user_touched. The version of the user to be saved is older than the current version.

### ISSUE THREAD

**Issue by LikeableHades** [Vekseid/ForumSessionProvider#5]
I installed this extension and started getting these errors: 
`[exception] [Xy3IyED6FYAXHKzOzl26kwAAAB0] /index.php?title=Test&action=submit   MWException from line 4014 of [REDACTED]/includes/user/User.php: CAS update failed on user_touched. The version of the user to be saved is older than the current version.`

The complete stacktrace is 

`#0 [REDACTED]/includes/libs/rdbms/database/Database.php(3967): User->{closure}(Wikimedia\Rdbms\DatabaseMysqli, string)
#1 [REDACTED]/includes/libs/rdbms/database/DBConnRef.php(68): Wikimedia\Rdbms\Database->doAtomicSection(string, Closure)
#2 [REDACTED]/includes/libs/rdbms/database/DBConnRef.php(635): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#3 [REDACTED]/includes/user/User.php(4025): Wikimedia\Rdbms\DBConnRef->doAtomicSection(string, Closure)
#4 [REDACTED]/extensions/ForumSessionProvider/ForumSessionProvider.php(513): User->saveSettings()
#5 [REDACTED]/extensions/ForumSessionProvider/ForumSessionProvider.php(429): ForumSessionProvider->setWikiGroups()
#6 [REDACTED]/includes/session/SessionManager.php(466): ForumSessionProvider->provideSessionInfo(WebRequest)
#7 [REDACTED]/includes/session/SessionManager.php(191): MediaWiki\Session\SessionManager->getSessionInfoForRequest(WebRequest)
#8 [REDACTED]/includes/WebRequest.php(806): MediaWiki\Session\SessionManager->getSessionForRequest(WebRequest)
#9 [REDACTED]/includes/session/SessionManager.php(129): WebRequest->getSession()
#10 [REDACTED]/includes/Setup.php(826): MediaWiki\Session\SessionManager::getGlobalSession()
#11 [REDACTED]/includes/WebStart.php(81): require_once(string)
#12 [REDACTED]/index.php(41): require(string)
#13 {main}`

This error has occurred on the latest Chrome, Firefox, and Microsoft Edge browsers. The forum it is linked to is SMF 2.0.15, with the wiki version being 1.34.2. PHP version 7.4.8. It can be resolved by commenting out lines 4014-4016 in /includes/user/User.php 
`throw new MWException( "CAS update failed on user_touched. " .
					"The version of the user to be saved is older than the current version."
				);`

**Comment by Vekseid** [comment]
Going to leave this open for now as I'm not certain your PR completely fixes this.

**Comment by LikeableHades** [comment]
Sounds good. It fixed it for me, but may not have for all users.
