### ISSUE TITLE
Does not work with SMF 2.1.2 and MediaWiki 1.38.2

### ISSUE THREAD

**Issue by strange-creature** [Vekseid/ForumSessionProvider#7]
I've tried to apply this extension for MediaWiki 1.38.2 to SMF 2.1.2 integration and got this:

```
[exception] [YucwylU9orYvSayCjqAsywAAAAg] /index.php?title=Main_Page   TypeError: Argument 1 passed to MediaWiki\Auth\TemporaryPasswordPrimaryAuthenticationProvider::__construct() must implement interface Wikimedia\Rdbms\ILoadBalancer, array given, called in /home/path1/public_html/site1/extensions/ForumSessionProvider/ForumAuthManager.php on line 27
#0 /home/path1/public_html/site1/extensions/ForumSessionProvider/ForumAuthManager.php(27): MediaWiki\Auth\TemporaryPasswordPrimaryAuthenticationProvider->__construct(array)
#1 /home/path1/public_html/site1/vendor/wikimedia/object-factory/src/ObjectFactory.php(247): ForumAuthManager->__construct()
#2 /home/path1/public_html/site1/vendor/wikimedia/object-factory/src/ObjectFactory.php(152): Wikimedia\ObjectFactory\ObjectFactory::getObjectFromSpec(array, array)
#3 /home/path1/public_html/site1/includes/auth/AuthManager.php(2401): Wikimedia\ObjectFactory\ObjectFactory->createObject(array, array)
#4 /home/path1/public_html/site1/includes/auth/AuthManager.php(2446): MediaWiki\Auth\AuthManager->providerArrayFromSpecs(string, array)
#5 /home/path1/public_html/site1/includes/auth/AuthManager.php(1016): MediaWiki\Auth\AuthManager->getPrimaryAuthenticationProviders()
#6 /home/path1/public_html/site1/includes/skins/SkinTemplate.php(620): MediaWiki\Auth\AuthManager->canCreateAccounts()
#7 /home/path1/public_html/site1/includes/skins/SkinTemplate.php(519): SkinTemplate->useCombinedLoginLink()
#8 /home/path1/public_html/site1/includes/skins/SkinTemplate.php(1252): SkinTemplate->buildPersonalUrls(boolean)
#9 /home/path1/public_html/site1/includes/skins/SkinTemplate.php(782): SkinTemplate->buildContentNavigationUrlsInternal()
#10 /home/path1/public_html/site1/includes/skins/SkinTemplate.php(202): SkinTemplate->getPortletsTemplateData()
#11 /home/path1/public_html/site1/includes/skins/SkinMustache.php(81): SkinTemplate->getTemplateData()
#12 /home/path1/public_html/site1/skins/Vector/includes/SkinVector.php(564): SkinMustache->getTemplateData()
#13 /home/path1/public_html/site1/includes/skins/SkinMustache.php(58): Vector\SkinVector->getTemplateData()
#14 /home/path1/public_html/site1/skins/Vector/includes/SkinVector.php(455): SkinMustache->generateHTML()
#15 /home/path1/public_html/site1/includes/skins/SkinTemplate.php(150): Vector\SkinVector->generateHTML()
#16 /home/path1/public_html/site1/includes/OutputPage.php(2807): SkinTemplate->outputPage()
#17 /home/path1/public_html/site1/includes/MediaWiki.php(926): OutputPage->output(boolean)
#18 /home/path1/public_html/site1/includes/MediaWiki.php(939): MediaWiki::{closure}()
#19 /home/path1/public_html/site1/includes/MediaWiki.php(563): MediaWiki->main()
#20 /home/path1/public_html/site1/index.php(53): MediaWiki->run()
#21 /home/a1
```

**Comment by strange-creature** [comment]
I guess it's similar as here: https://github.com/SimpleMachines/smf-mw-auth/issues/20
